on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  stl_build:
    runs-on: ubuntu-latest
    name: Build stl
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: OpenSCAD STL build rpi3 top
        id: openscad-rpi3-top
        uses: pkoehlers/openscad-Build-action@v1
        with:
          input-file: 'rpi_case.scad'
          output-file: 'rpi3_case_top.stl'
          customizer-parameter-file: 'rpi_case.json'
          customizer-parameter-set: 'rpi3_case_top'
      - name: OpenSCAD STL build rpi3 bottom
        id: openscad-rpi3-bottom
        uses: pkoehlers/openscad-Build-action@v1
        with:
          input-file: 'rpi_case.scad'
          output-file: 'rpi3_case_bottom.stl'
          customizer-parameter-file: 'rpi_case.json'
          customizer-parameter-set: 'rpi3_case_bottom'
      - name: OpenSCAD STL build rpi3 top with antenna
        id: openscad-rpi3-top-with-antenna
        uses: pkoehlers/openscad-Build-action@v1
        with:
          input-file: 'rpi_case.scad'
          output-file: 'rpi3_case_top_with_antenna.stl'
          customizer-parameter-file: 'rpi_case.json'
          customizer-parameter-set: 'rpi3_case_top_with_antenna'
      - name: OpenSCAD STL build rpi4 top
        id: openscad-rpi4-top
        uses: pkoehlers/openscad-Build-action@v1
        with:
          input-file: 'rpi_case.scad'
          output-file: 'rpi4_case_top.stl'
          customizer-parameter-file: 'rpi_case.json'
          customizer-parameter-set: 'rpi4_case_top'
      - name: OpenSCAD STL build rpi4 bottom
        id: openscad-rpi4-bottom
        uses: pkoehlers/openscad-Build-action@v1
        with:
          input-file: 'rpi_case.scad'
          output-file: 'rpi4_case_bottom.stl'
          customizer-parameter-file: 'rpi_case.json'
          customizer-parameter-set: 'rpi4_case_bottom'
      - name: OpenSCAD STL build rpi4 top with antenna
        id: openscad-rpi4-top-with-antenna
        uses: pkoehlers/openscad-Build-action@v1
        with:
          input-file: 'rpi_case.scad'
          output-file: 'rpi4_case_top_with_antenna.stl'
          customizer-parameter-file: 'rpi_case.json'
          customizer-parameter-set: 'rpi4_case_top_with_antenna'
      - name: Archive stl outputs
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: |
            rpi3_case_top.stl
            rpi3_case_bottom.stl
            rpi3_case_top_with_antenna.stl
            rpi4_case_top.stl
            rpi4_case_bottom.stl
            rpi4_case_top_with_antenna.stl
